name: Add Comment on PR regarding merge conflicts with next branch

on:
  pull_request:
    branch: [ branch_1 ]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    env:
      LATEST_COMMIT_ID: git log --format="%H" -n 1
    steps:
      - name: check-conflicts
        run: |
          echo $LATEST_COMMIT_ID
          git config user.email "syncbranchbot@microsoft.com"
          git config user.name "Sync-Branch Bot"
          git fetch origin branch_2
          git checkout branch_2
          git merge $LATEST_COMMIT_ID
  add-comment:
    runs-on: ubuntu-latest
    needs: [check-conflicts]
    if: needs.check-conflicts.result != 'failure'
    steps:
      - name:  add-conflict-comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'You might have to revisit this PR to resolve conflicts with the next branch!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
