# https://www.youtube.com/watch?v=XxufR0fjj8Y
# https://github.com/marketplace/actions/send-job-status-to-azure-queue
# https://github.community/t/avoiding-conflicts-when-two-workflows-push-to-the-same-branch/233774/8

name: Push To Main

on:
  push:
    branch: [ branch_1 ]

jobs:
  workflow:
    name: Workflow name
    run: | 
      echo ${{ github.workflow }}
      echo ${{ github.head_ref }}
      echo ${{ github.run_id }}
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 350
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: |
          echo "Starting Code Build"
          sleep 2m
          echo "Finish Code Build"

  deploy:
    name: Deploy
    # concurrency:
    #   group: deployment
    #   cancel-in-progress: false
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: |
          echo "Deploying the code"
          sleep 2m
          echo "Finish deployment"
