name: Push commit to Azure Queue

on:
  push:
    branch: [ test_main ]

jobs:
  queue-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name != 'do-not-merge-in-next' }} && ${{ github.repository_owner }} == 'microsoft'
    steps:
      - run:
          echo ${{ github.event.pull_request.number }}
      - run: npm install @azure/storage-queue
      - uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da # pin@v6
        with:
          script: |
            const { QueueClient, QueueServiceClient } = require('@azure/storage-queue')
            const connectionString = `${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}`;
            const queueName = `${{ secrets.AZURE_QUEUE_NAME }}`;
            const queueServiceClient = QueueServiceClient.fromConnectionString(connectionString);
            const queueClient = queueServiceClient.getQueueClient(queueName);
            console.log("SHA-----", `${{ github.sha }}`);
            console.log("SHA-----", `${{ github.actor }}`);
            const message = {
              sha: `${{ github.sha }}`,
              author: `${{ github.actor }}`,
              label: `queued`,
            };
            await queueClient.sendMessage(JSON.stringify(message));
  add-comment:
    runs-on: ubuntu-latest
    needs: [ queue-pr ]
    steps:
      - run: npm install @octokit/core
      - name: Create Comment on PR
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/core");
            const pr = '${{ github.event.pull_request.number }}';
            const token = `${{ secrets.GITHUB_TOKEN }}`;
            const octokit = new Octokit({ auth: token });
            await octokit.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews', {
              owner: 'sonalivdeshpande',
              repo: 'FluidFramework',
              pull_number: pr,
              body: 'This commit is queued for merging with the `test_next` branch! Please ignore this PR for now. Contact @microsoft/fluid-cr-infra for help.',
              event: 'COMMENT',
            })
