name: Sync branches
on:
  push:
    branches: branch_1

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checking branches for merge conflicts
        id: mergeconflict
        run: |
            git init
            git checkout $TARGET_BRANCH
            git merge $SOURCE_BRANCH
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_BRANCH: "branch_1"
          TARGET_BRANCH: "branch_2"
  feedback-conflicts:
    runs-on: ubuntu-latest
    needs: [check-conflicts]
    if: always() && (needs.check-conflicts.result == 'failure')
    steps:
      - name: Opening pull request to resolve merge conflic
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "branch_1"
          TO_BRANCH: "branch_2"
