name: Sync branches
on:
  push:
    branches: branch_1
  issue_comment:
    types: created
  repository_dispatch:
    types: sync-branch
  workflow_dispatch:
    inputs:
      branch_name:
        description: branch_2
        required: true

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
    - name: Use node version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
        fetch-depth: 0
    - run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
        git fetch origin branch_2
        git merge origin/branch_1 --no-ff
        git push
  create-comment-failure:
    runs-on: ubuntu-latest
    needs: [feedback-conflicts]
    if: needs.feedback-conflicts.result == 'failure'
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            **You have a merge conflict with branch_2. Please resolve these conflicts!!**
          allow-repeats: true
  feedback-conflicts:
    runs-on: ubuntu-latest
    needs: [check-conflicts]
    if: needs.check-conflicts.result == 'failure'
    steps:
      - name: Opening pull request to resolve merge conflicts
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "branch_1"
          TO_BRANCH: "branch_2"

#
