# name: Sync
# on:
#   push:
#     branches:
#       - branch_1

# jobs:
#   sync-branches:
#     runs-on: ubuntu-latest
#     name: Syncing branches
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Set up Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       # open PR if there are merge conflicts
#       # - name: Opening pull request
#       #   id: pull
#       #   uses: tretuna/sync-branches@1.4.0
#       #   with:
#       #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       #     FROM_BRANCH: "branch_1"
#       #     TO_BRANCH: "branch_2"

name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"