name: Sync branches
on:
  push:
    branches: branch_1
  issue_comment:
    types: created

jobs:
  check-conflicts:
    runs-on: ubuntu:latest
    steps:
      - name: Checking branches for merge conflicts
        run: |
            git fetch
            git checkout branch_2
            git merge branch_1
  feedback-conflicts:
    runs-on: ubuntu-latest
    needs: [check-conflicts]
    if: needs.check-conflicts.result == 'failure'
    steps:
      - name: Opening pull request to resolve merge conflicts
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "branch_1"
          TO_BRANCH: "branch_2"
  create-comment:
    runs-on: ubuntu-latest
    needs: [feedback-conflicts]
    if: needs.feedback-conflicts.result != 'failure'
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            **You have a merge conflict with branch_2. Please resolve these conflicts!!**
          allow-repeats: true
#
