name: Sync
on:
  push:
    branches:
      - branch_1

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # - id: conflict
      #   name: Find merge conflicts
      #   uses: olivernybroe/action-conflict-finder@v2.0
      #   env: 
      #     GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      # - name: conflict-feedback
      #   if: steps.conflict.outputs.result == true
      #   run: |
      #     echo "Merge conflict exists"
      #   with:
      #     name: Opening pull request
      #     id: pull
      #     uses: tretuna/sync-branches@1.4.0
      #     with:
      #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #       FROM_BRANCH: "branch_1"
      #       TO_BRANCH: "branch_2"      
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env: 
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      - name: automerge-feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"

      