name: Sync main and next branch
on:
  push:
    branches: [ branch_1 ]
  pull_request:
    branches: [ branch_2 ]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Conflict Check
      # https://github.com/apache/cloudstack/blob/main/.github/workflows/merge-conflict-checker.yml
        uses: eps1lon/actions-label-merge-conflict@v2.0.0  
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          dirtyLabel: "status:has-conflicts"
          removeOnDirtyLabel: "status:needs-attention"
          continueOnMissingPermissions: true
          commentOnDirty: "Hi @${{ github.event.pull_request.user.login }}, your pull request has merge conflicts. Can you fix the conflicts and sync your branch with the base branch?"
      # https://github.com/marketplace/actions/automatically-merge-pr    
      - name: Automatically Merge PR
        uses: tibdex/sync-branches@v1 # https://github.com/marketplace/actions/auto-merge-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # merge-method: merge
          # do-not-merge-labels: never-merge
          # required-labels: automerge
          # pull-request: ${{ github.event.inputs.pull-request }}
          # dry-run: false